# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import burpextender_pb2 as burpextender__pb2


class CallFuncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallFunc = channel.unary_unary(
                '/CallFuncService/CallFunc',
                request_serializer=burpextender__pb2.Request.SerializeToString,
                response_deserializer=burpextender__pb2.Response.FromString,
                )


class CallFuncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallFunc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallFuncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallFunc': grpc.unary_unary_rpc_method_handler(
                    servicer.CallFunc,
                    request_deserializer=burpextender__pb2.Request.FromString,
                    response_serializer=burpextender__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CallFuncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CallFuncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallFunc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CallFuncService/CallFunc',
            burpextender__pb2.Request.SerializeToString,
            burpextender__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
